-- MySQL Script generated by MySQL Workbench
-- Mon May 29 09:40:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pmt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pmt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pmt` ;

-- -----------------------------------------------------
-- Table `pmt`.`issue_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`issue_details` (
  `Issue_Id` INT NOT NULL AUTO_INCREMENT,
  `Issue_name` TEXT NULL DEFAULT NULL,
  `Description` VARCHAR(100) NULL DEFAULT NULL,
  `Comment` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Issue_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`defect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`defect` (
  `defect_ID` INT NOT NULL,
  `Issue_ID` INT NULL DEFAULT NULL,
  `Description` VARCHAR(100) NULL DEFAULT NULL,
  `Status` VARCHAR(50) NULL DEFAULT NULL,
  `defect_SD` DATE NULL DEFAULT NULL,
  `defect_ED` DATE NULL DEFAULT NULL,
  `Planned_Hours` VARCHAR(30) NOT NULL,
  `Actual_Hours` VARCHAR(30) NOT NULL,
  `Comments` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`defect_ID`),
  INDEX `Issue_ID` (`Issue_ID` ASC) VISIBLE,
  CONSTRAINT `defect_ibfk_1`
    FOREIGN KEY (`Issue_ID`)
    REFERENCES `pmt`.`issue_details` (`Issue_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`file` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `file_link` VARCHAR(100) NULL DEFAULT NULL,
  `issue_id` INT NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `issue_id` (`issue_id` ASC) VISIBLE,
  CONSTRAINT `file_ibfk_1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `pmt`.`issue_details` (`Issue_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`project_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`project_manager` (
  `pm_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Email_ID` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`pm_ID`),
  UNIQUE INDEX `Email_ID` (`Email_ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`project_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`project_details` (
  `Project_ID` INT NOT NULL AUTO_INCREMENT,
  `pm_ID` INT NULL DEFAULT NULL,
  `Project_Name` VARCHAR(20) NOT NULL,
  `Project_Description` VARCHAR(100) NOT NULL,
  `Planned_SD` DATETIME NOT NULL,
  `Planned_ED` DATETIME NOT NULL,
  `Actual_SD` DATETIME NOT NULL,
  `Actual_ED` DATETIME NOT NULL,
  `Planned_Hours` VARCHAR(30) NOT NULL,
  `Actual_Hours` VARCHAR(30) NOT NULL,
  `Status` ENUM('To_do', 'In_Progress', 'In_Review', 'Done') NULL DEFAULT 'To_do',
  `Project_Lead` VARCHAR(20) NULL DEFAULT NULL,
  `Client_Name` VARCHAR(20) NULL DEFAULT NULL,
  `Comments` VARCHAR(100) NULL DEFAULT NULL,
  `Risk` VARCHAR(50) NULL DEFAULT NULL,
  `Mitigation` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Project_ID`),
  INDEX `pm_ID` (`pm_ID` ASC) VISIBLE,
  CONSTRAINT `project_details_ibfk_1`
    FOREIGN KEY (`pm_ID`)
    REFERENCES `pmt`.`project_manager` (`pm_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`team_memb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`team_memb` (
  `tm_ID` INT NOT NULL AUTO_INCREMENT,
  `pm_ID` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Email_ID` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `Contact` INT NOT NULL,
  PRIMARY KEY (`tm_ID`),
  UNIQUE INDEX `Email_ID` (`Email_ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 50001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`issue_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`issue_member` (
  `issueMember_id` INT NOT NULL AUTO_INCREMENT,
  `issue_ID` INT NOT NULL,
  `tm_ID` INT NOT NULL,
  `project_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`issueMember_id`),
  INDEX `project_ID` (`project_ID` ASC) VISIBLE,
  INDEX `issue_ID` (`issue_ID` ASC) VISIBLE,
  INDEX `tm_ID` (`tm_ID` ASC) VISIBLE,
  CONSTRAINT `issue_member_ibfk_1`
    FOREIGN KEY (`project_ID`)
    REFERENCES `pmt`.`project_details` (`Project_ID`),
  CONSTRAINT `issue_member_ibfk_2`
    FOREIGN KEY (`issue_ID`)
    REFERENCES `pmt`.`issue_details` (`Issue_Id`),
  CONSTRAINT `issue_member_ibfk_3`
    FOREIGN KEY (`tm_ID`)
    REFERENCES `pmt`.`team_memb` (`tm_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`issueworkflow_connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`issueworkflow_connection` (
  `sr_no` INT NOT NULL AUTO_INCREMENT,
  `issue_id` INT NOT NULL,
  `workflow_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`sr_no`),
  INDEX `issue_id` (`issue_id` ASC) VISIBLE,
  CONSTRAINT `issueworkflow_connection_ibfk_1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `pmt`.`issue_details` (`Issue_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`project_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`project_member` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `tm_ID` INT NOT NULL,
  `Project_ID` INT NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `Project_ID` (`Project_ID` ASC) VISIBLE,
  INDEX `tm_ID` (`tm_ID` ASC) VISIBLE,
  CONSTRAINT `project_member_ibfk_1`
    FOREIGN KEY (`Project_ID`)
    REFERENCES `pmt`.`project_details` (`Project_ID`),
  CONSTRAINT `project_member_ibfk_2`
    FOREIGN KEY (`tm_ID`)
    REFERENCES `pmt`.`team_memb` (`tm_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`projectworkflow_connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`projectworkflow_connection` (
  `sr_no` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `workflow_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`sr_no`),
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `projectworkflow_connection_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `pmt`.`project_details` (`Project_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`task` (
  `Task_ID` INT NOT NULL,
  `Issue_ID` INT NULL DEFAULT NULL,
  `Description` VARCHAR(100) NULL DEFAULT NULL,
  `Status` ENUM('To_do', 'In_Progress', 'In_Review', 'Done') NULL DEFAULT NULL,
  `task_SD` DATE NULL DEFAULT NULL,
  `task_ED` DATE NULL DEFAULT NULL,
  `Planned_Hours` VARCHAR(30) NOT NULL,
  `Actual_Hours` VARCHAR(30) NOT NULL,
  `Priority` VARCHAR(50) NULL DEFAULT NULL,
  `Comments` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Task_ID`),
  INDEX `Issue_ID` (`Issue_ID` ASC) VISIBLE,
  CONSTRAINT `task_ibfk_1`
    FOREIGN KEY (`Issue_ID`)
    REFERENCES `pmt`.`issue_details` (`Issue_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pmt`.`workflow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmt`.`workflow` (
  `workflow_name` VARCHAR(20) NULL DEFAULT NULL,
  `prev_state` VARCHAR(20) NULL DEFAULT NULL,
  `current_state` VARCHAR(20) NULL DEFAULT NULL,
  `next_state` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
